# ===== STAGE 1: BUILD =====
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# copia tudo
COPY . .

# gera o jar
RUN mvn clean package -DskipTests


# ===== STAGE 2: RUN =====
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# copia apenas o jar gerado
COPY --from=build /app/target/*.jar app.jar

# expõe porta
EXPOSE 8082

# comando de execução
ENTRYPOINT ["java", "-jar", "app.jar"]